### ISSUE TITLE
Derived work question

### ISSUE THREAD

**Issue by SharpSeeEr** [benbeadle/modular-redux-thunk#9]
I found this package when looking for a better way to organize my redux store.  The api you created is almost exactly what I had thought of. I forked this project so I could look around and make changes, ultimately changing almost everything.  After that I realized I still wanted something a bit simpler.

So I created a fresh project with new code, that is much simpler. because I omit a lot of the functionality this package provides.  However, the concepts from your project were inspiration for my new project, and I used some sections of your README.

I really want to make sure you are credited as needed.  How do you think that is best accomplished?  I am open to suggestions.  Thanks!

The new project is here:  https://github.com/SharpSeeEr/redux-duck-modules.

**Comment by benbeadle** [comment]
Hey @SharpSeeEr,

Thanks for taking the time out of your day to ensure you properly credit others' work - much appreciated.

Like your project, my package was inspired by someone else's work and I had similar concerns. My solution was to link to the other repo in the first sentence of my README - that way it's clear and upfront where my inspiration came from.

I admit it may not be the "best" solution, but I am always open to suggestions like yourself :)

- Ben

P.S. I'll close in a few days if no more questions/comments!
